### ISSUE TITLE
Run Code After Player Finishes

### ISSUE THREAD

**Issue by shadowcatzero** [JasperVanEsveld/discordeno-audio-plugin#5]
Currently I have a local copy of this that exposes the raw player so I can await `onDone()` to continue code after the song / video finishes. Is there a good way to do this that I'm missing? If not, I think this would be pretty useful. Maybe also a way to run code when the entire queue finishes.

I'd guess this would be very easy to do by adding a method to the queue player called onDone that just returns the raw player's onDone, but I'm not sure if there are any weird consequences.

**Comment by JasperVanEsveld** [comment]
Great suggestion!
Check out `1.2.6` which adds a few events.
I did some refactors so it is not quite the same as awaiting `onDone()` (that function no longer exists) but similar enough

These are the events:
`done` which works similar to what you suggested.
`next` triggered when a now song/sound starts
`loop` triggered when a song/sound is restarted

Instead of awaiting you can just pass a callback:
```js
const disconnect = your_bot.helpers
  .getPlayer("your guild id")
  .on("next", ({title}) => console.log(`Next up: ${title}`));
```
Calling disconnect will cause it to stop listening.

**Comment by shadowcatzero** [comment]
Awesome, thanks! This plugin is nice to use and works well.
